version: "3.8"
services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: how_to_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      APP_KEY: "base64:oS3M4w3cKbPs3a+mvE1+qmdQ5+ovZmz6bIg194Dm5sA="
      APP_ENV: "local"
      APP_DEBUG: "true"
      DB_CONNECTION: "mongodb"
      DB_HOST: "mongodb"
      DB_PORT: "27017"
      DB_DATABASE: "how_to_db"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_URI: "mongodb://root:root@mongodb:27017/how_to_db?authSource=admin"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "how_to_db"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
