version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    container_name: how_to_frontend
    ports:
      - "3000:3000"
    # network_mode: "host"
    depends_on:
      - backend
    command: npm run dev -- --host
    # explicitly expose frontend service to all interfaces
    # command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
      # :delegated
    container_name: how_to_backend
    ports:
      - "80:80"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
