version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/usr/src/app
    container_name: how_to_frontend
    ports:
      - "3000:3000"
    # networks:
    #   - how_to_network
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # environment:
    #   - DB_CONNECTION=mongodb
    #   - DB_HOST=mongodb
    #   - DB_PORT=27017
    #   - DB_DATABASE=how_to_db
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=
    volumes:
      - ./backend:/var/www/html
      # :delegated
    container_name: how_to_backend
    # networks:
    #   - how_to_network
    ports:
      - "8080:80"
    # networks:
    #   - how_to_network
    # - how_to_db
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      # - mongodb_data:/data/db
      - mongodb_data:/var/lib/mongodb
      # - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - DB_DATABASE=how_to_db
      - DB_USERNAME=root
      - DB_PASSWORD=
    # networks:
    #   - how_to_db
    # env_file:
    #   - backend/.env

volumes:
  # how_to_network:
  #   driver: bridge
  mongodb_data:
