name: deploy frontend and backend
on:
  push:
jobs:
  netlify-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './frontend/dist'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  railway-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
        railwayProjectId: ${{ secrets.RAILWAY_PROJECT_ID }}
        railwayToken: ${{ secrets.RAILWAY_TOKEN }}
        service: "how-to"


          
